"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Hand-written (not autogenerated) to mirror app/models/*.py exactly. If you
have a real Postgres available, sanity-check this against autogenerate the
first time you touch the schema:

    alembic upgrade head
    alembic revision --autogenerate -m "sanity check"

...and confirm the generated diff is empty (or only cosmetic constraint-name
differences) before deleting that throwaway revision.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ---------------------------------------------------------------- categories
    op.create_table(
        "categories",
        sa.Column("id", sa.String(30), nullable=False),
        sa.Column("label", sa.String(60), nullable=False),
        sa.Column("icon", sa.String(60), nullable=False, server_default=""),
        sa.Column("color", sa.String(30), nullable=False, server_default=""),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.PrimaryKeyConstraint("id", name="pk_categories"),
    )

    # ---------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("role", sa.String(20), nullable=False, server_default="user"),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("kyc_status", sa.String(20), nullable=False, server_default="not_started"),
        sa.Column("kyc_provider_ref", sa.String(255), nullable=True),
        sa.Column("account_status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("region_code", sa.String(10), nullable=True),
        sa.Column("is_real_money_eligible", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("totp_secret", sa.String(64), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    # ---------------------------------------------------------------- markets
    # NOTE: resolved_outcome_id -> market_outcomes.id is added as a deferred
    # FK after market_outcomes exists (circular dependency between the two
    # tables).
    op.create_table(
        "markets",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("slug", sa.String(160), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("category_id", sa.String(30), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="upcoming"),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("resolution_source", sa.Text(), nullable=True),
        sa.Column("resolution_criteria", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("tags", postgresql.ARRAY(sa.String(40)), nullable=False, server_default="{}"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source", sa.String(20), nullable=False, server_default="admin"),
        sa.Column("review_status", sa.String(20), nullable=False, server_default="approved"),
        sa.Column("resolved_outcome_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payouts_processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_markets"),
        sa.UniqueConstraint("slug", name="uq_markets_slug"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], name="fk_markets_category_id_categories"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_markets_created_by_users", ondelete="SET NULL"
        ),
    )
    op.create_index("ix_markets_slug", "markets", ["slug"])
    op.create_index("ix_markets_status", "markets", ["status"])
    op.create_index("ix_markets_category_status", "markets", ["category_id", "status"])

    # ---------------------------------------------------------------- market_outcomes
    op.create_table(
        "market_outcomes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("label", sa.String(20), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("id", name="pk_market_outcomes"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_market_outcomes_market_id_markets", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_market_outcomes_market_id", "market_outcomes", ["market_id"])

    # Deferred FK: markets.resolved_outcome_id -> market_outcomes.id
    op.create_foreign_key(
        "fk_markets_resolved_outcome_id_market_outcomes",
        "markets",
        "market_outcomes",
        ["resolved_outcome_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ---------------------------------------------------------------- market_stats
    op.create_table(
        "market_stats",
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("liquidity", sa.Numeric(18, 4), nullable=False, server_default="0"),
        sa.Column("total_volume", sa.Numeric(18, 4), nullable=False, server_default="0"),
        sa.Column("volume_24h", sa.Numeric(18, 4), nullable=False, server_default="0"),
        sa.Column("trader_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("market_id", name="pk_market_stats"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_market_stats_market_id_markets", ondelete="CASCADE"
        ),
    )

    # ---------------------------------------------------------------- price_history
    op.create_table(
        "price_history",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outcome_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("price", sa.Numeric(6, 4), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_price_history"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_price_history_market_id_markets", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name="fk_price_history_outcome_id_market_outcomes",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_price_history_ts", "price_history", ["ts"])
    op.create_index("ix_price_history_market_ts", "price_history", ["market_id", "ts"])

    # ---------------------------------------------------------------- reports
    op.create_table(
        "reports",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reported_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_reports"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_reports_market_id_markets", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reported_by"], ["users.id"], name="fk_reports_reported_by_users", ondelete="CASCADE"
        ),
    )

    # ---------------------------------------------------------------- refresh_tokens
    op.create_table(
        "refresh_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(128), nullable=False),
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_refresh_tokens_user_id_users", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    # ---------------------------------------------------------------- password_reset_tokens
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_password_reset_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_password_reset_tokens_token_hash"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_password_reset_tokens_user_id_users", ondelete="CASCADE"
        ),
    )

    # ---------------------------------------------------------------- email_verification_tokens
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_email_verification_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_email_verification_tokens_token_hash"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_email_verification_tokens_user_id_users", ondelete="CASCADE"
        ),
    )

    # ---------------------------------------------------------------- amm_pools
    op.create_table(
        "amm_pools",
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("liquidity_param", sa.Numeric(18, 6), nullable=False),
        sa.Column("outcome_shares", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("subsidy_remaining", sa.Numeric(18, 4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("market_id", name="pk_amm_pools"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_amm_pools_market_id_markets", ondelete="CASCADE"
        ),
    )

    # ---------------------------------------------------------------- orders
    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outcome_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("side", sa.String(4), nullable=False),
        sa.Column("order_type", sa.String(10), nullable=False),
        sa.Column("time_in_force", sa.String(3), nullable=False, server_default="GTC"),
        sa.Column("limit_price", sa.Numeric(6, 4), nullable=True),
        sa.Column("shares_requested", sa.Numeric(18, 6), nullable=False),
        sa.Column("shares_filled", sa.Numeric(18, 6), nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        sa.Column("idempotency_key", sa.String(128), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_orders"),
        sa.UniqueConstraint("idempotency_key", name="uq_orders_idempotency_key"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_orders_user_id_users", ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_orders_market_id_markets", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name="fk_orders_outcome_id_market_outcomes",
            ondelete="RESTRICT",
        ),
    )
    op.create_index("ix_orders_status", "orders", ["status"])
    op.create_index("ix_orders_user_id", "orders", ["user_id"])
    op.create_index(
        "ix_orders_book_lookup", "orders", ["market_id", "outcome_id", "side", "status", "limit_price"]
    )

    # ---------------------------------------------------------------- trades
    op.create_table(
        "trades",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outcome_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("taker_order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("maker_order_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("fill_source", sa.String(12), nullable=False),
        sa.Column("price", sa.Numeric(6, 4), nullable=False),
        sa.Column("shares", sa.Numeric(18, 6), nullable=False),
        sa.Column("taker_side", sa.String(4), nullable=False),
        sa.Column("buyer_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("seller_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("fee", sa.Numeric(18, 4), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_trades"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_trades_market_id_markets", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name="fk_trades_outcome_id_market_outcomes",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["taker_order_id"], ["orders.id"], name="fk_trades_taker_order_id_orders", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["maker_order_id"], ["orders.id"], name="fk_trades_maker_order_id_orders", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["buyer_user_id"], ["users.id"], name="fk_trades_buyer_user_id_users", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["seller_user_id"], ["users.id"], name="fk_trades_seller_user_id_users", ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_trades_created_at", "trades", ["created_at"])
    op.create_index("ix_trades_market_created", "trades", ["market_id", "created_at"])

    # ---------------------------------------------------------------- positions
    op.create_table(
        "positions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outcome_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("shares", sa.Numeric(18, 6), nullable=False, server_default="0"),
        sa.Column("avg_price", sa.Numeric(6, 4), nullable=False, server_default="0"),
        sa.Column("invested", sa.Numeric(18, 4), nullable=False, server_default="0"),
        sa.Column("status", sa.String(10), nullable=False, server_default="open"),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payout_idempotency_key", sa.String(128), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_positions"),
        sa.UniqueConstraint("payout_idempotency_key", name="uq_positions_payout_idempotency_key"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_positions_user_id_users", ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_positions_market_id_markets", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name="fk_positions_outcome_id_market_outcomes",
            ondelete="RESTRICT",
        ),
    )
    op.create_index("ix_positions_status", "positions", ["status"])
    op.create_index(
        "uq_positions_open_per_user_market_outcome",
        "positions",
        ["user_id", "market_id", "outcome_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )

    # ---------------------------------------------------------------- accounts
    op.create_table(
        "accounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("owner_type", sa.String(30), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.PrimaryKeyConstraint("id", name="pk_accounts"),
        sa.UniqueConstraint("owner_type", "owner_id", "currency", name="uq_accounts_owner_currency"),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name="fk_accounts_owner_id_users", ondelete="RESTRICT"
        ),
    )

    # ---------------------------------------------------------------- ledger_entries
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("transaction_group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("direction", sa.String(6), nullable=False),
        sa.Column("amount", sa.Numeric(18, 4), nullable=False),
        sa.Column("reason", sa.String(30), nullable=False),
        sa.Column("ref_type", sa.String(30), nullable=True),
        sa.Column("ref_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ledger_entries"),
        sa.CheckConstraint("amount > 0", name="ck_ledger_entries_positive_amount"),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name="fk_ledger_entries_account_id_accounts", ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_ledger_entries_account_id", "ledger_entries", ["account_id"])
    op.create_index("ix_ledger_entries_transaction_group_id", "ledger_entries", ["transaction_group_id"])
    op.create_index("ix_ledger_entries_ref", "ledger_entries", ["ref_type", "ref_id"])

    # ---------------------------------------------------------------- payments
    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("direction", sa.String(12), nullable=False),
        sa.Column("method", sa.String(12), nullable=False),
        sa.Column("processor", sa.String(20), nullable=False),
        sa.Column("processor_ref", sa.String(255), nullable=True),
        sa.Column("amount", sa.Numeric(18, 4), nullable=False),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(12), nullable=False, server_default="pending"),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column("failure_reason", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_payments"),
        sa.UniqueConstraint("idempotency_key", name="uq_payments_idempotency_key"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_payments_user_id_users", ondelete="RESTRICT"),
    )
    op.create_index("ix_payments_user_id", "payments", ["user_id"])

    # ---------------------------------------------------------------- market_signals
    op.create_table(
        "market_signals",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("category_id", sa.String(30), nullable=True),
        sa.Column("source", sa.String(30), nullable=False),
        sa.Column("signal_key", sa.String(60), nullable=False),
        sa.Column("value", postgresql.JSONB(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_market_signals"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_market_signals_market_id_markets", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_market_signals_collected_at", "market_signals", ["collected_at"])
    op.create_index("ix_market_signals_market_collected", "market_signals", ["market_id", "collected_at"])

    # ---------------------------------------------------------------- ai_recommendations
    op.create_table(
        "ai_recommendations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outcome_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("current_price", sa.Numeric(6, 4), nullable=False),
        sa.Column("target_price", sa.Numeric(6, 4), nullable=False),
        sa.Column("expected_return", sa.Numeric(8, 4), nullable=False),
        sa.Column("reasoning", sa.String(600), nullable=False),
        sa.Column("risk_level", sa.String(10), nullable=False),
        sa.Column("timeframe", sa.String(60), nullable=False),
        sa.Column("signals", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("model_name", sa.String(60), nullable=False),
        sa.Column("prompt_version", sa.String(20), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("review_status", sa.String(20), nullable=False, server_default="pending_review"),
        sa.Column("reviewed_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.String(500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ai_recommendations"),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name="fk_ai_recommendations_market_id_markets", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name="fk_ai_recommendations_outcome_id_market_outcomes",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name="fk_ai_recommendations_reviewed_by_users", ondelete="SET NULL"
        ),
    )
    op.create_index("ix_ai_recommendations_review_status", "ai_recommendations", ["review_status"])

    # ---------------------------------------------------------------- ai_market_drafts
    op.create_table(
        "ai_market_drafts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("category_id", sa.String(30), nullable=False),
        sa.Column("proposed_end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("resolution_source", sa.Text(), nullable=False),
        sa.Column("resolution_criteria", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(60), nullable=False),
        sa.Column("prompt_version", sa.String(20), nullable=False),
        sa.Column("review_status", sa.String(20), nullable=False, server_default="pending_review"),
        sa.Column("reviewed_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.String(500), nullable=True),
        sa.Column("created_market_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ai_market_drafts"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name="fk_ai_market_drafts_category_id_categories"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name="fk_ai_market_drafts_reviewed_by_users", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_market_id"],
            ["markets.id"],
            name="fk_ai_market_drafts_created_market_id_markets",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_ai_market_drafts_review_status", "ai_market_drafts", ["review_status"])

    # ---------------------------------------------------------------- audit_log
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(60), nullable=False),
        sa.Column("target_type", sa.String(40), nullable=True),
        sa.Column("target_id", sa.String(64), nullable=True),
        sa.Column("before", postgresql.JSONB(), nullable=True),
        sa.Column("after", postgresql.JSONB(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_audit_log"),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name="fk_audit_log_actor_user_id_users", ondelete="SET NULL"
        ),
    )

    # ---------------------------------------------------------------- leaderboard_snapshot
    op.create_table(
        "leaderboard_snapshot",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("portfolio_value", sa.Numeric(18, 4), nullable=False),
        sa.Column("total_pnl", sa.Numeric(18, 4), nullable=False),
        sa.Column("total_pnl_percent", sa.Numeric(10, 4), nullable=False),
        sa.Column("volume", sa.Numeric(18, 4), nullable=False),
        sa.Column("markets_traded", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("win_rate", sa.Numeric(6, 4), nullable=False, server_default="0"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="pk_leaderboard_snapshot"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_leaderboard_snapshot_user_id_users", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_leaderboard_snapshot_rank", "leaderboard_snapshot", ["rank"])


def downgrade() -> None:
    op.drop_table("leaderboard_snapshot")
    op.drop_table("audit_log")
    op.drop_table("ai_market_drafts")
    op.drop_table("ai_recommendations")
    op.drop_table("market_signals")
    op.drop_table("payments")
    op.drop_table("ledger_entries")
    op.drop_table("accounts")
    op.drop_table("positions")
    op.drop_table("trades")
    op.drop_table("orders")
    op.drop_table("amm_pools")
    op.drop_table("email_verification_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("reports")
    op.drop_table("price_history")
    op.drop_table("market_stats")
    op.drop_constraint("fk_markets_resolved_outcome_id_market_outcomes", "markets", type_="foreignkey")
    op.drop_table("market_outcomes")
    op.drop_table("markets")
    op.drop_table("users")
    op.drop_table("categories")
